### ISSUE TITLE
Request for publishing a new version from the main branch

### ISSUE THREAD

**Issue by weihanglo** [jonhoo/repackage#3]
`repackage@0.1.1` depends on `cargo_toml@0.9.0`, which can't handle boolean values in `package.readme`.

Starting from Rust 1.80.0, Cargo “normalizes” Cargo.toml when publish. This process includes filling in `readme = false`. See <https://github.com/rust-lang/cargo/pull/13713>.

The main branch has already depended on `cargo_toml@0.15.0`, so the fix is as simple as publishing one new version :)

---

I know you might not really use this package anymore, but you definitely understand something happened, and we need the fix. Thank you :)

**Comment by weihanglo** [comment]
cc @lovesegfault and @Eh2406 

I don't know if you have merge permission on this repo, but it seems that you both are the owner of the package on crates.io

**Comment by Eh2406** [comment]
`Owner user weihanglo has been invited to be an owner of crate repackage`

**Comment by weihanglo** [comment]
A PR is up: https://github.com/jonhoo/repackage/pull/4
